#!/bin/bash
echo "*********************************************************"
echo "Running git pre-commit hook. Running Static analysis... "
echo "*********************************************************"

gradlew ktlintCheck

status=$?

if [ "$status" = 0 ] ; then
    echo "Static analysis found no problems."
    if git rev-parse --verify HEAD >/dev/null 2>&1
    then
	    against=HEAD
    else
	      # Initial commit: diff against an empty tree object
	      against=$(git hash-object -t tree /dev/null)
    fi
    allownonascii=$(git config --type=bool hooks.allownonascii)
    exec 1>&2

    if [ "$allownonascii" != "true" ] &&
	  # Note that the use of brackets around a tr range is ok here, (it's
	  # even required, for portability to Solaris 10's /usr/bin/tr), since
  	# the square bracket bytes happen to fall in the designated range.
  	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
	  then
	      cat <<\EOF
	      Error: Attempt to add a non-ASCII file name.

    This can cause problems if you want to work with people on other platforms.

    To be portable it is advisable to rename the file.

    If you know what you are doing you can disable this check using:

      git config hooks.allownonascii true
EOF
        exit 1
    fi

    # If there are whitespace errors, print the offending file names and fail.
    exec git diff-index --check --cached $against --



    exit 0
else
    echo "*********************************************************"
    echo "       ********************************************      "
    echo 1>&2 "Static analysis found violations it could not fix."
    echo "Run ./gradlew ktlintFormat to fix formatting related issues..."
    echo "       ********************************************      "
    echo "*********************************************************"
    exit 1
fi
